name: Test Build

on:
  push:
    branches: [main]

jobs:
  test-build:
    name: Test Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: List files before build
        run: |
          echo "Files before build:"
          ls -la

      - name: Build application
        run: |
          echo "Starting Next.js build..."
          npm run build
          echo "Build completed successfully"
        env:
          NODE_ENV: production
          NEXT_PUBLIC_GA_ID: ${{ secrets.NEXT_PUBLIC_GA_ID || '' }}
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL || '' }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY || '' }}

      - name: List files after build
        run: |
          echo "Files after build:"
          ls -la
          echo "Checking .next directory:"
          if [ -d ".next" ]; then
            echo "✅ .next directory exists"
            ls -la .next/
            echo "Size of .next directory:"
            du -sh .next/
          else
            echo "❌ .next directory does not exist"
          fi

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: test-build-files
          path: .next/
          if-no-files-found: error
          retention-days: 1
